title: Notes
author: Florin Stancu
email: florin@stancu.me
description: Byte-sized insights from a Software Engineer

disqus:
  shortname: notes-stancu-me
  
google_analytics: G-R19RHYK07D
github_username: StancuFlorin
instagram_username: stancuflorin

theme: minima
